apiVersion: apps/v1
kind: Deployment
metadata:
#  name: {{ .Values.spec.app }}-deployment
  name: finspect-deployment
  namespace: myapp
spec:
  revisionHistoryLimit: 3
#{{- if not .Values.autoscaling.enabled }}
#{{- if not true }}
#  replicas: {{ .Values.replicaCount }}
  replicas: 4
#{{- end }}
  selector:
    matchLabels:
#      app: {{ .Values.spec.app }}
      app: finspect-monitoring
  template:
    metadata:
      labels:
#        app: {{ .Values.spec.app }}
        app: finspect-monitoring
    spec:
#      affinity:
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#            - podAffinityTerm:
#                labelSelector:
#                  matchLabels:
#                    app: {{ .Values.spec.app }}
#                topologyKey: topology.kubernetes.io/zone
#              weight: 100
#            - podAffinityTerm:
#                labelSelector:
#                  matchLabels:
#                    app: {{ .Values.spec.app }}
#                topologyKey: kubernetes.io/hostname
#              weight: 100
#      priorityClassName: {{ .Values.priorityClass }}
#      volumes:
#        - name: app-config-volume
#          configMap:
#            name: {{ .Values.configMap }}
      containers:
#        - name: {{ .Values.spec.app }}-container
        - name: finspect-monitoring-container
#          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          image: nedeesh/monitoring:1.0.0
          imagePullPolicy: Always
#          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
#            - containerPort: {{ .Values.spec.container.port }}
            - containerPort: 8080
              name: http
#          env:
#            - name: SPRING_CONFIG_LOCATION
#              value: {{ .Values.springConfigLocation }}
#            - name: ACCERTIFY_SECRET
#              valueFrom:
#                secretKeyRef:
#                  name: {{ .Values.sealedsecret.accerytifyPwSecret.name }}
#                  key: accertify-authentication-pw
#            - name: SPRING_PROFILES_ACTIVE
#              value: {{ .Values.environment | quote }}
#          volumeMounts:
#            - name: app-config-volume
#              mountPath: {{ .Values.mountPath }}
#          {{- with .Values.resources }}
#          resources:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: {{ .Values.spec.container.port }}
#            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
#            successThreshold: {{ .Values.livenessProbe.successThreshold }}
#            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
#            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
#            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: {{ .Values.spec.container.port }}
#            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
#            successThreshold: {{ .Values.readinessProbe.successThreshold }}
#            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
#            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
#            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}

