apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-persistent-storage
spec:
  capacity:
    storage: 5Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/c/finVol/tms-fs-service.log"
#    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube