---
apiVersion: v1
kind: Service
metadata:
  name: finspect-monitoring-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.spec.app }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http